DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS players CASCADE;

CREATE TABLE teams
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255),
    created_by          VARCHAR(255),
    created_on          date,
    account             BIGINT,
    transfer_commission INT,
    CONSTRAINT pk_teams PRIMARY KEY (id)
);

CREATE TABLE players
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    dob        date,
    experience INT,
    team_id    BIGINT,
    CONSTRAINT pk_players PRIMARY KEY (id)
);

ALTER TABLE players
    ADD CONSTRAINT FK_PLAYERS_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);
